### ISSUE TITLE
Simple documentation

### ISSUE THREAD

**Issue by ShalokShalom** [adafruit/Adafruit_Python_Shell#19]
Hi there :)

First - the API documentation is well hidden, and its almost impossible to find on the README. :)
Second - I miss simple examples, particularly about sending shell commands and receiving their outputs. 

The API documentation seems to be a bit too elaborate for me, thanks.

**Comment by ShalokShalom** [comment]
Wonderful. I would mostly like to understand, how to simply launch a command, and how to get stderr and stdout back 😃

**Comment by makermelissa** [comment]
The best example script is probably https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/main/adafruit-pitft.py. The main function for running commands is:
```run_command(self, cmd, suppress_message=False, return_output=False)```

Stderr and stdout are combined in the function (though they call different functions to write the message back to the console). All output is returned if `return_output` is `True` and it is not printed to the console if `suppress_message` is `True`.

**Comment by ShalokShalom** [comment]
Do we want to include this in the readthedocs?

**Comment by makermelissa** [comment]
Eventually. I think the code just needs to have someone (probably me) go through it and have docstrings added for the public functions or at least the more commonly used ones.

**Comment by ShalokShalom** [comment]
Well, that would be more API documentation. I mean docs who can be read by the average Joe. Something you would include in a Readme. Something like a quick start. 👍🏻
